### ISSUE TITLE
Hamburger Icon

### ISSUE THREAD

**Issue by zacck-zz** [zacck/consulting-site#3]
Set the hamburger menu colour to something more contrasty like the yellow or pink of the logotype. the current grey is quite low contrast so it's hard to see. 
Try to have the hamburger on the same side as the nav drawer. currently the hamburger icon is on the right but the menu comes out on the left. 
The headline text on the main image is cool but also needs to contrast a bit better with the bg image. Maybe try a background colour here?

**Comment by TarCode** [comment]
https://github.com/TarCode/consulting-site/commit/0f60ac4644e5bd5d02b7a7395034b0c452d6a7ee

**Comment by zacck-zz** [comment]
woot woot pR please 🗡
