### ISSUE TITLE
Footer Section

### ISSUE THREAD

**Issue by zacck-zz** [zacck/consulting-site#5]
That last section with Launch Design and the Links column - since there is only one link, consider removing this section entirely and putting the github link in the footer before the 'designed by' bit. also, link to your page :slightly_smiling_face: currently it sends me to the main page.

**Comment by TarCode** [comment]
https://github.com/TarCode/consulting-site/commit/8b20d4e71fe9000428e65c4bb9ceadc25c558440

**Comment by zacck-zz** [comment]
@TarCode  awe could you pr to this repo please so I can merge
